#
# new-issue-welcome
# https://github.com/behaviorbot/new-issue-welcome
#

# Комментарий, который отправляется при создании первой задачи новым пользователем
newIssueWelcomeComment: |
  👋 Спасибо за то, что создали вашу первую задачу здесь! Если вы сообщаете о 🐞 баге, убедитесь, что вы заполнили все поля в шаблоне задачи, чтобы мы могли вам лучше помочь.

  Мы получаем множество задач в этом репозитории, поэтому, пожалуйста, будьте терпеливы, и мы вернемся к вам, как только сможем.

#
# new-pr-welcome
# https://github.com/behaviorbot/new-pr-welcome
#

# Комментарий, который отправляется при создании первого PR новым участником
newPRWelcomeComment: |
  💖 Спасибо за ваш первый запрос на слияние! 💖

  Вот список того, что поможет довести его до завершения:
  - Запустите `yarn lint` локально, чтобы проверить ошибки форматирования. Это автоматически исправит некоторые ошибки, выполните коммит и отправьте изменения.
  - Запустите `yarn test` локально, чтобы проверить ошибки. Это гарантирует, что все компоненты ведут себя как ожидается.
  - Запустите `yarn start`, чтобы локально запустить сайт документации и проверить несколько страниц, убедившись, что все работает корректно.
  - Добавьте тесты при изменении/добавлении функциональности.

  Мы получаем множество запросов на слияние в этом репозитории, поэтому, пожалуйста, будьте терпеливы, и мы вернемся к вам, как только сможем.

#
# first-pr-merge
# https://github.com/behaviorbot/first-pr-merge
#

# Комментарий, который отправляется при успешном слиянии первого PR пользователя
firstPRMergeComment: |
  Поздравляем с успешным слиянием вашего первого PR! 🎉🎉🎉

  ![танцующий робот](https://media.giphy.com/media/tczJoRU7XwBS8/giphy.gif)

#
# lock-threads
# https://github.com/dessant/lock-threads
#

# Количество дней бездействия перед автоматической блокировкой закрытой задачи или PR
daysUntilLock: 365

# Комментарий, который добавляется перед блокировкой. Установите `false`, чтобы отключить
lockComment: >
  Эта ветка была автоматически заблокирована, так как не было активности в течение продолжительного времени. Пожалуйста, создайте новую задачу для связанных ошибок и добавьте ссылки на соответствующие комментарии в этой ветке.

# Ограничение только для `issues` или `pulls` (по умолчанию оба)
# only: issues
