# Через сколько дней после бездействия задача/PR считается устаревшей
daysUntilStale: 30

# Через сколько дней после пометки "устаревшая" задача/PR будет закрыта
daysUntilClose: 7

# Сообщение, добавляемое к устаревшей задаче/PR
staleMessage: 'Эта задача/PR помечена как устаревшая из-за отсутствия активности. Если это ошибка, пожалуйста, прокомментируйте, чтобы она была повторно открыта.'

# Сообщение, добавляемое при закрытии задачи/PR
closeMessage: 'Эта задача/PR была автоматически закрыта, так как не было активности в течение продолжительного времени.'

# Помечать ли только задачи (issues), но не pull requests
only: issues

# Метка, добавляемая к устаревшим задачам/PR
staleLabel: 'stale'

# Исключить задачи с определенными метками
exemptLabels:
  - 'pinned'
  - 'important'

# Исключить определенные авторы
exemptAssignees:
  - 'maintainer1'

# Игнорировать задачи, открытые недавно
exemptAllAssignees: false

# Уведомления о действиях (для отладки)
debugOnly: false
