name: Bug Report v2
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Текст шаблона для отправки!
  - type: input
    id: script_path
    attributes:
      label: Скрипт/Плагин
      description: Укажите путь до скрипта(плагин) или его название
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Что случилось?
      description: Укажаите подробное описание проблемы.
      placeholder: Ошибка...
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: steps_to_bug
    attributes:
      label: Как инициировать ошибку?
      description: Подробно опишите шаги чтобы инициировать ошибку.
      placeholder: Во время работы...
      value: "A bug happened!"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Логи ошибки
      description: Скопируйте и вставье лог ошибки.
      render: shell
    validations:
      required: false
