name: Release
'on':
  push:
    branches:
      - master
  workflow_dispatch:

env:
  ARTIFACT_DIR: ./artifacts

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  release:
    name: Publish releaser
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/actions/setup-env
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install WASM Target
        run: rustup target add wasm32-wasip1
        shell: bash
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: './packages/charm-swc/ -> target'

      - name: Build
        run: yarn build
        shell: bash
      - name: Publish via releaser (Pre-release)
        if: github.ref != 'refs/heads/master'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASER_MODE: 'prerelease'
        run: |
          yarn releaser
      - name: Publish via releaser
        if: github.ref == 'refs/heads/master'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASER_MODE: 'release'
        run: |
          yarn releaser
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ${{ env.ARTIFACT_DIR }}
